import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1780382923512 implements MigrationInterface {
    name = 'Baseline1780382923512'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "display_name" character varying(255) NOT NULL, "avatar_url" character varying(500), "role" character varying(20) NOT NULL DEFAULT 'member', "token_version" integer NOT NULL DEFAULT '0', "password_reset_token" character varying(255), "password_reset_expires" TIMESTAMP WITH TIME ZONE, "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_user_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "project_members" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "user_id" integer NOT NULL, "role" character varying(20) NOT NULL DEFAULT 'member', "added_by" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_project_member" UNIQUE ("project_id", "user_id"), CONSTRAINT "PK_0b2f46f804be4aea9234c78bcc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_pm_user" ON "project_members" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "projects" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "prefix" character varying(5) NOT NULL, "description" text, "status" character varying(20) NOT NULL DEFAULT 'active', "lead_id" integer, "default_assignee_id" integer, "item_counter" integer NOT NULL DEFAULT '0', "default_sprint_duration" integer NOT NULL DEFAULT '14', "estimation_scale" character varying(10) NOT NULL DEFAULT 'free', "last_activity_at" TIMESTAMP WITH TIME ZONE, "archived_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f40fa53e9ebd3988a62b69ddd9f" UNIQUE ("prefix"), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_project_status" ON "projects" ("status") `);
        await queryRunner.query(`CREATE TABLE "project_statuses" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "name" character varying(50) NOT NULL, "category" character varying(20) NOT NULL, "color" character varying(7) NOT NULL DEFAULT '#6B7280', "sort_order" integer NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "wip_limit" integer NOT NULL DEFAULT '0', "is_fixed" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_status_name_project" UNIQUE ("project_id", "name"), CONSTRAINT "PK_b0ca0748cbeddc71d6bf76c2fa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ps_project" ON "project_statuses" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "labels" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "name" character varying(15) NOT NULL, "color" character varying(7) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_label_name_project" UNIQUE ("project_id", "name"), CONSTRAINT "PK_c0c4e97f76f1f3a268c7a70b925" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_label_project" ON "labels" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "sprints" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "name" character varying(255) NOT NULL, "goal" text, "status" character varying(20) NOT NULL DEFAULT 'planning', "start_date" date, "end_date" date, "sprint_number" integer NOT NULL, "created_by" integer, "completed_at" TIMESTAMP WITH TIME ZONE, "carry_over_policy" character varying(16) NOT NULL DEFAULT 'ask', "capacity" integer, "started_by" integer, "started_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_sprint_number_project" UNIQUE ("project_id", "sprint_number"), CONSTRAINT "PK_6800aa2e0f508561812c4b9afb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_sprint_one_active_per_project" ON "sprints" ("project_id") WHERE status = 'active'`);
        await queryRunner.query(`CREATE INDEX "IDX_sprint_status" ON "sprints" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_sprint_project" ON "sprints" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "comments" ("id" SERIAL NOT NULL, "work_item_id" integer NOT NULL, "author_id" integer NOT NULL, "body" text NOT NULL, "edited_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_comment_work_item" ON "comments" ("work_item_id") `);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" SERIAL NOT NULL, "work_item_id" integer NOT NULL, "uploaded_by" integer NOT NULL, "original_filename" character varying(500) NOT NULL, "storage_key" character varying(1000) NOT NULL, "mime_type" character varying(100) NOT NULL, "size_bytes" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_attachment_work_item" ON "attachments" ("work_item_id") `);
        await queryRunner.query(`CREATE TABLE "work_items" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "item_number" integer NOT NULL, "item_type" character varying(10) NOT NULL, "parent_id" integer, "title" character varying(500) NOT NULL, "description" text, "user_story" text, "status_id" integer NOT NULL, "priority" character varying(10) NOT NULL DEFAULT 'medium', "sprint_id" integer, "story_points" integer, "estimated_at" TIMESTAMP WITH TIME ZONE, "approved_by" integer, "approved_at" TIMESTAMP WITH TIME ZONE, "assignee_id" integer, "reporter_id" integer NOT NULL, "reviewer_id" integer, "deleted_at" TIMESTAMP WITH TIME ZONE, "sort_order" character varying(255) NOT NULL DEFAULT 'n', "start_date" date, "end_date" date, "completed_at" TIMESTAMP WITH TIME ZONE, "epic_state" character varying(16) NOT NULL DEFAULT 'draft', "archived_at" TIMESTAMP WITH TIME ZONE, "added_mid_sprint" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_afbfa01728533c866eafaf6f160" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_wi_project_type" ON "work_items" ("project_id", "item_type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_wi_project_number" ON "work_items" ("project_id", "item_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_wi_status" ON "work_items" ("status_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_wi_assignee" ON "work_items" ("assignee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_wi_item_type" ON "work_items" ("item_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_wi_sprint" ON "work_items" ("sprint_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_wi_parent" ON "work_items" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_wi_project" ON "work_items" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "work_item_watchers" ("work_item_id" integer NOT NULL, "user_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_2b7d46bc71445fb6638820058aa" PRIMARY KEY ("work_item_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_work_item_watchers_user" ON "work_item_watchers" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "work_item_associations" ("id" SERIAL NOT NULL, "item_id" integer NOT NULL, "linked_item_id" integer NOT NULL, "link_type" character varying(20) NOT NULL, "created_by" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_association" UNIQUE ("item_id", "linked_item_id", "link_type"), CONSTRAINT "PK_f45728043b6ba22ffd20528c6ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_assoc_created_by" ON "work_item_associations" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_assoc_type" ON "work_item_associations" ("link_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_assoc_linked" ON "work_item_associations" ("linked_item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_assoc_item" ON "work_item_associations" ("item_id") `);
        await queryRunner.query(`CREATE TABLE "story_release_notes" ("id" SERIAL NOT NULL, "work_item_id" integer NOT NULL, "body" text NOT NULL DEFAULT '', "published_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9d2f172548e124608c79b83ba14" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_release_note_work_item" ON "story_release_notes" ("work_item_id") `);
        await queryRunner.query(`CREATE TABLE "checklist_items" ("id" SERIAL NOT NULL, "work_item_id" integer NOT NULL, "title" character varying(500) NOT NULL, "is_completed" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_bae00945a1d4789bd648e583e29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_checklist_work_item" ON "checklist_items" ("work_item_id") `);
        await queryRunner.query(`CREATE TABLE "work_item_acceptance_criteria" ("id" SERIAL NOT NULL, "work_item_id" integer NOT NULL, "given_text" text NOT NULL, "when_text" text, "then_text" text, "is_met" boolean NOT NULL DEFAULT false, "verified_by" integer, "verified_at" TIMESTAMP WITH TIME ZONE, "linked_item_id" integer, "sort_order" character varying(255) NOT NULL DEFAULT 'n', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ab59f99e6da0b8b999d6036b582" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac_work_item" ON "work_item_acceptance_criteria" ("work_item_id") `);
        await queryRunner.query(`CREATE TABLE "sprint_scope_changes" ("id" SERIAL NOT NULL, "sprint_id" integer NOT NULL, "work_item_id" integer, "action" character varying(10) NOT NULL, "story_points" integer, "actor_id" integer, "note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3386bdf70d17e95cd5fb7bd22a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_scope_sprint" ON "sprint_scope_changes" ("sprint_id") `);
        await queryRunner.query(`CREATE TABLE "sprint_daily_snapshots" ("id" SERIAL NOT NULL, "sprint_id" integer NOT NULL, "snapshot_date" date NOT NULL, "total_points" integer NOT NULL DEFAULT 0, "completed_points" integer NOT NULL DEFAULT 0, "in_progress_points" integer NOT NULL DEFAULT 0, "scope_added_points" integer NOT NULL DEFAULT 0, "scope_removed_points" integer NOT NULL DEFAULT 0, "item_counts_by_status" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_snapshot_sprint_date" UNIQUE ("sprint_id", "snapshot_date"), CONSTRAINT "PK_sprint_daily_snapshots" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "sprint_daily_snapshots" ADD CONSTRAINT "FK_snapshot_sprint" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TABLE "retro_cards" ("id" SERIAL NOT NULL, "retrospective_id" integer NOT NULL, "column" character varying(20) NOT NULL, "content" text NOT NULL, "author_id" integer NOT NULL, "votes" integer NOT NULL DEFAULT '0', "is_action_item" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_99d3f8630f6583c6a3146268ba8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_retro_card_retro" ON "retro_cards" ("retrospective_id") `);
        await queryRunner.query(`CREATE TABLE "retrospectives" ("id" SERIAL NOT NULL, "sprint_id" integer NOT NULL, "project_id" integer NOT NULL, "created_by" integer, "facilitator_id" integer, "opened_at" TIMESTAMP WITH TIME ZONE, "closed_at" TIMESTAMP WITH TIME ZONE, "max_votes_per_user" integer NOT NULL DEFAULT '5', "authors_revealed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_1bf0d2fa606f1e04d8bf1ce2bc" UNIQUE ("sprint_id"), CONSTRAINT "PK_bb2dfd48493b3906269b2de23c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_retro_sprint" ON "retrospectives" ("sprint_id") `);
        await queryRunner.query(`CREATE TABLE "retro_votes" ("id" SERIAL NOT NULL, "card_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "UQ_retro_vote" UNIQUE ("card_id", "user_id"), CONSTRAINT "PK_864e553892d2fcedfb30176099f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "type" character varying(50) NOT NULL, "reference_type" character varying(20) NOT NULL, "reference_id" integer NOT NULL, "project_id" integer, "title" character varying(255) NOT NULL, "body" text, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_notif_read" ON "notifications" ("user_id", "is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_notif_user" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "project_integrations" ("id" BIGSERIAL NOT NULL, "project_id" integer NOT NULL, "type" character varying(20) NOT NULL, "config" jsonb NOT NULL DEFAULT '{}'::jsonb, "secret" character varying(128) NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" integer, CONSTRAINT "PK_29ea92f0dabc66c54182df0777f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_integrations_project_enabled" ON "project_integrations" ("project_id") `);
        await queryRunner.query(`CREATE TABLE "integration_deliveries" ("id" BIGSERIAL NOT NULL, "integration_id" bigint NOT NULL, "event_type" character varying(40) NOT NULL, "payload" jsonb NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'pending', "http_status" integer, "attempts" integer NOT NULL DEFAULT '0', "next_attempt_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "delivered_at" TIMESTAMP WITH TIME ZONE, "last_error" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d8ccb7a6e471cdb4ec5a3972ed6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_deliveries_integration" ON "integration_deliveries" ("integration_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_deliveries_pickup" ON "integration_deliveries" ("next_attempt_at") `);
        await queryRunner.query(`CREATE TABLE "comment_reactions" ("id" BIGSERIAL NOT NULL, "comment_id" integer NOT NULL, "user_id" integer NOT NULL, "emoji" character varying(8) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d10c03282d5280fe55f0bb67563" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_comment_reactions_comment" ON "comment_reactions" ("comment_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_comment_reactions" ON "comment_reactions" ("comment_id", "user_id", "emoji") `);
        await queryRunner.query(`CREATE TABLE "comment_mentions" ("id" BIGSERIAL NOT NULL, "comment_id" integer NOT NULL, "user_id" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_96cd7c00d35e056fcebb7725e02" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_comment_mentions_user" ON "comment_mentions" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_comment_mentions" ON "comment_mentions" ("comment_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "token" character varying(500) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_refresh_token_user" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_refresh_token" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE TABLE "instance_settings" ("key" character varying(100) NOT NULL, "value" text NOT NULL, "updated_by" integer, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f4841fbd4c9819d5ade4b5dfeb8" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" SERIAL NOT NULL, "email" character varying(255) NOT NULL, "token" character varying(500) NOT NULL, "role" character varying(20) NOT NULL DEFAULT 'member', "project_id" integer, "invited_by" integer NOT NULL, "status" character varying(10) NOT NULL DEFAULT 'pending', "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_invitation_pending_email" ON "invitations" ("email") WHERE status = 'pending'`);
        await queryRunner.query(`CREATE INDEX "IDX_invite_email" ON "invitations" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_invite_token" ON "invitations" ("token") `);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" SERIAL NOT NULL, "project_id" integer NOT NULL, "work_item_id" integer, "user_id" integer NOT NULL, "action" character varying(50) NOT NULL, "field_changed" character varying(50), "old_value" text, "new_value" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_activity_created" ON "activity_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_activity_project" ON "activity_logs" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_activity_work_item" ON "activity_logs" ("work_item_id") `);
        await queryRunner.query(`CREATE TABLE "work_item_labels" ("work_item_id" integer NOT NULL, "label_id" integer NOT NULL, CONSTRAINT "PK_7074aae12877d30bbcfad890374" PRIMARY KEY ("work_item_id", "label_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_366aa1ac10b3b35e3e9ec33596" ON "work_item_labels" ("work_item_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f19b2cc88f10c181cee4768ca0" ON "work_item_labels" ("label_id") `);
        await queryRunner.query(`CREATE TABLE "pinned_projects" ("user_id" integer NOT NULL, "project_id" integer NOT NULL, "pinned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_pinned_projects" PRIMARY KEY ("user_id", "project_id"))`);
        await queryRunner.query(`CREATE TABLE "project_visits" ("user_id" integer NOT NULL, "project_id" integer NOT NULL, "visited_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_project_visits" PRIMARY KEY ("user_id", "project_id"))`);
        await queryRunner.query(`ALTER TABLE "pinned_projects" ADD CONSTRAINT "FK_pinned_projects_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pinned_projects" ADD CONSTRAINT "FK_pinned_projects_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_visits" ADD CONSTRAINT "FK_project_visits_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_visits" ADD CONSTRAINT "FK_project_visits_project" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_f92749a9dcdd54f83bdde8edfd5" FOREIGN KEY ("lead_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_statuses" ADD CONSTRAINT "FK_12e48935c08ebc5ba11ec26d6bf" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_68b0da461f6765824f6db642f12" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_82145010051f3f2fc94671c0b35" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_8a8c060865f55dbf82aac62a1f4" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_c232d9ee9df92ddd801ed929f88" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attachments" ADD CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58" FOREIGN KEY ("uploaded_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_items" ADD CONSTRAINT "FK_5546d4f73bf19d6e7fba13b59a7" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_items" ADD CONSTRAINT "FK_a295bab46dcf3e0265f6b8c3098" FOREIGN KEY ("parent_id") REFERENCES "work_items"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_items" ADD CONSTRAINT "FK_0b92ed84dd33cded6b78dd3d600" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_items" ADD CONSTRAINT "FK_2222c947792edf802196155655b" FOREIGN KEY ("status_id") REFERENCES "project_statuses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_items" ADD CONSTRAINT "FK_f2504d84b418c258b342c853478" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_items" ADD CONSTRAINT "FK_36d87ee28c8695b43dc3827c54e" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_item_watchers" ADD CONSTRAINT "FK_05468b5283c702fc6e4ae22d110" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_item_watchers" ADD CONSTRAINT "FK_8162483de2f381373c479c516c3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_item_associations" ADD CONSTRAINT "FK_ef061a6c4631f6d472979c77ee5" FOREIGN KEY ("item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_item_associations" ADD CONSTRAINT "FK_eb59983447a91deaebe0a2fb541" FOREIGN KEY ("linked_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_item_associations" ADD CONSTRAINT "FK_2920ab1c1a569221223f8fe9820" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "story_release_notes" ADD CONSTRAINT "FK_c6cefbeb5a68bbf103b433b8913" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "checklist_items" ADD CONSTRAINT "FK_b383c72a0ffbebfc657096ea9e2" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_item_acceptance_criteria" ADD CONSTRAINT "FK_a27bbf6ebc409e8406014e70fdc" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_item_acceptance_criteria" ADD CONSTRAINT "FK_f68baea6fc42c4e160956fd52ba" FOREIGN KEY ("verified_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_item_acceptance_criteria" ADD CONSTRAINT "FK_9d72f01138c578f8deb7a003eca" FOREIGN KEY ("linked_item_id") REFERENCES "work_items"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprint_scope_changes" ADD CONSTRAINT "FK_e9ca443db8b6f0ca08e7ecc4e27" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retro_cards" ADD CONSTRAINT "FK_ccaa72f2f2b17b7d24184bb9cf1" FOREIGN KEY ("retrospective_id") REFERENCES "retrospectives"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retro_cards" ADD CONSTRAINT "FK_03ea2c7ea94899df7357446196d" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retrospectives" ADD CONSTRAINT "FK_1bf0d2fa606f1e04d8bf1ce2bc8" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retrospectives" ADD CONSTRAINT "FK_f9daef8ab34b3868051aa385bb1" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retro_votes" ADD CONSTRAINT "FK_8708046296ea133ebd0fab388a0" FOREIGN KEY ("card_id") REFERENCES "retro_cards"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retro_votes" ADD CONSTRAINT "FK_fb54789fd56e320f183665f56e5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_integrations" ADD CONSTRAINT "FK_b4dbc08660e1c1fb75911d9448e" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_integrations" ADD CONSTRAINT "FK_7d330f76da76fd961341c597b11" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "integration_deliveries" ADD CONSTRAINT "FK_b966bceaaa1eb5c17c6bcfd8388" FOREIGN KEY ("integration_id") REFERENCES "project_integrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_reactions" ADD CONSTRAINT "FK_dc714054fc62b698018fcb0ae37" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_reactions" ADD CONSTRAINT "FK_481c40600b2ee590adb27abb0e6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" ADD CONSTRAINT "FK_9ac3fac766fa09176e5c53e4d3f" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" ADD CONSTRAINT "FK_a29d739a2d28fb38b8b591f8152" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invitations" ADD CONSTRAINT "FK_29b1cef6891d9b9d4e35f793b81" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_3baa1aae6f896f72eafbdd057e9" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_d54f841fa5478e4734590d44036" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_item_labels" ADD CONSTRAINT "FK_366aa1ac10b3b35e3e9ec33596d" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "work_item_labels" ADD CONSTRAINT "FK_f19b2cc88f10c181cee4768ca0b" FOREIGN KEY ("label_id") REFERENCES "labels"("id") ON DELETE CASCADE ON UPDATE CASCADE`);

        await queryRunner.query(`
            ALTER TABLE "work_items" ADD COLUMN "search_vector" tsvector
            GENERATED ALWAYS AS (
                setweight(to_tsvector('english', coalesce("title", '')), 'A') ||
                setweight(to_tsvector('english', coalesce("description", '')), 'B')
            ) STORED
        `);
        await queryRunner.query(`CREATE INDEX "IDX_wi_search" ON "work_items" USING gin("search_vector")`);

        await queryRunner.query(`
            CREATE UNIQUE INDEX "UQ_notif_daily_dedup"
            ON "notifications" ("user_id", "type", "reference_id", (("created_at" AT TIME ZONE 'UTC')::date))
            WHERE "type" IN ('sprint_ending', 'task_due_soon', 'task_overdue')
        `);

        await queryRunner.query(`UPDATE "work_items" SET "epic_state" = 'draft' WHERE "item_type" = 'epic' AND "epic_state" IS NULL`);

        await queryRunner.query(`CREATE TABLE IF NOT EXISTS "typeorm_metadata" ("type" varchar NOT NULL, "database" varchar, "schema" varchar, "table" varchar, "name" varchar, "value" text)`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("type", "database", "schema", "table", "name", "value") VALUES ('GENERATED_COLUMN', 'trackero', 'public', 'work_items', 'search_vector', $1)`, [`setweight(to_tsvector('english', coalesce("title", '')), 'A') || setweight(to_tsvector('english', coalesce("description", '')), 'B')`]);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "work_item_labels" DROP CONSTRAINT "FK_f19b2cc88f10c181cee4768ca0b"`);
        await queryRunner.query(`ALTER TABLE "work_item_labels" DROP CONSTRAINT "FK_366aa1ac10b3b35e3e9ec33596d"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_d54f841fa5478e4734590d44036"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_3baa1aae6f896f72eafbdd057e9"`);
        await queryRunner.query(`ALTER TABLE "invitations" DROP CONSTRAINT "FK_29b1cef6891d9b9d4e35f793b81"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" DROP CONSTRAINT "FK_a29d739a2d28fb38b8b591f8152"`);
        await queryRunner.query(`ALTER TABLE "comment_mentions" DROP CONSTRAINT "FK_9ac3fac766fa09176e5c53e4d3f"`);
        await queryRunner.query(`ALTER TABLE "comment_reactions" DROP CONSTRAINT "FK_481c40600b2ee590adb27abb0e6"`);
        await queryRunner.query(`ALTER TABLE "comment_reactions" DROP CONSTRAINT "FK_dc714054fc62b698018fcb0ae37"`);
        await queryRunner.query(`ALTER TABLE "integration_deliveries" DROP CONSTRAINT "FK_b966bceaaa1eb5c17c6bcfd8388"`);
        await queryRunner.query(`ALTER TABLE "project_integrations" DROP CONSTRAINT "FK_7d330f76da76fd961341c597b11"`);
        await queryRunner.query(`ALTER TABLE "project_integrations" DROP CONSTRAINT "FK_b4dbc08660e1c1fb75911d9448e"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "retro_votes" DROP CONSTRAINT "FK_fb54789fd56e320f183665f56e5"`);
        await queryRunner.query(`ALTER TABLE "retro_votes" DROP CONSTRAINT "FK_8708046296ea133ebd0fab388a0"`);
        await queryRunner.query(`ALTER TABLE "retrospectives" DROP CONSTRAINT "FK_f9daef8ab34b3868051aa385bb1"`);
        await queryRunner.query(`ALTER TABLE "retrospectives" DROP CONSTRAINT "FK_1bf0d2fa606f1e04d8bf1ce2bc8"`);
        await queryRunner.query(`ALTER TABLE "retro_cards" DROP CONSTRAINT "FK_03ea2c7ea94899df7357446196d"`);
        await queryRunner.query(`ALTER TABLE "retro_cards" DROP CONSTRAINT "FK_ccaa72f2f2b17b7d24184bb9cf1"`);
        await queryRunner.query(`ALTER TABLE "sprint_scope_changes" DROP CONSTRAINT "FK_e9ca443db8b6f0ca08e7ecc4e27"`);
        await queryRunner.query(`ALTER TABLE "work_item_acceptance_criteria" DROP CONSTRAINT "FK_9d72f01138c578f8deb7a003eca"`);
        await queryRunner.query(`ALTER TABLE "work_item_acceptance_criteria" DROP CONSTRAINT "FK_f68baea6fc42c4e160956fd52ba"`);
        await queryRunner.query(`ALTER TABLE "work_item_acceptance_criteria" DROP CONSTRAINT "FK_a27bbf6ebc409e8406014e70fdc"`);
        await queryRunner.query(`ALTER TABLE "checklist_items" DROP CONSTRAINT "FK_b383c72a0ffbebfc657096ea9e2"`);
        await queryRunner.query(`ALTER TABLE "story_release_notes" DROP CONSTRAINT "FK_c6cefbeb5a68bbf103b433b8913"`);
        await queryRunner.query(`ALTER TABLE "work_item_associations" DROP CONSTRAINT "FK_2920ab1c1a569221223f8fe9820"`);
        await queryRunner.query(`ALTER TABLE "work_item_associations" DROP CONSTRAINT "FK_eb59983447a91deaebe0a2fb541"`);
        await queryRunner.query(`ALTER TABLE "work_item_associations" DROP CONSTRAINT "FK_ef061a6c4631f6d472979c77ee5"`);
        await queryRunner.query(`ALTER TABLE "work_item_watchers" DROP CONSTRAINT "FK_8162483de2f381373c479c516c3"`);
        await queryRunner.query(`ALTER TABLE "work_item_watchers" DROP CONSTRAINT "FK_05468b5283c702fc6e4ae22d110"`);
        await queryRunner.query(`ALTER TABLE "work_items" DROP CONSTRAINT "FK_36d87ee28c8695b43dc3827c54e"`);
        await queryRunner.query(`ALTER TABLE "work_items" DROP CONSTRAINT "FK_f2504d84b418c258b342c853478"`);
        await queryRunner.query(`ALTER TABLE "work_items" DROP CONSTRAINT "FK_2222c947792edf802196155655b"`);
        await queryRunner.query(`ALTER TABLE "work_items" DROP CONSTRAINT "FK_0b92ed84dd33cded6b78dd3d600"`);
        await queryRunner.query(`ALTER TABLE "work_items" DROP CONSTRAINT "FK_a295bab46dcf3e0265f6b8c3098"`);
        await queryRunner.query(`ALTER TABLE "work_items" DROP CONSTRAINT "FK_5546d4f73bf19d6e7fba13b59a7"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_e25812e3fd9b3f3edf11b2c5d58"`);
        await queryRunner.query(`ALTER TABLE "attachments" DROP CONSTRAINT "FK_c232d9ee9df92ddd801ed929f88"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_8a8c060865f55dbf82aac62a1f4"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_82145010051f3f2fc94671c0b35"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_68b0da461f6765824f6db642f12"`);
        await queryRunner.query(`ALTER TABLE "project_statuses" DROP CONSTRAINT "FK_12e48935c08ebc5ba11ec26d6bf"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_f92749a9dcdd54f83bdde8edfd5"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`DROP TABLE "project_visits"`);
        await queryRunner.query(`DROP TABLE "pinned_projects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f19b2cc88f10c181cee4768ca0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_366aa1ac10b3b35e3e9ec33596"`);
        await queryRunner.query(`DROP TABLE "work_item_labels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_activity_work_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_activity_project"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_activity_created"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invite_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_invite_email"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_invitation_pending_email"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP TABLE "instance_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_refresh_token_user"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_comment_mentions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_comment_mentions_user"`);
        await queryRunner.query(`DROP TABLE "comment_mentions"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_comment_reactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_comment_reactions_comment"`);
        await queryRunner.query(`DROP TABLE "comment_reactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deliveries_pickup"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_deliveries_integration"`);
        await queryRunner.query(`DROP TABLE "integration_deliveries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_integrations_project_enabled"`);
        await queryRunner.query(`DROP TABLE "project_integrations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notif_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notif_read"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "retro_votes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_retro_sprint"`);
        await queryRunner.query(`DROP TABLE "retrospectives"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_retro_card_retro"`);
        await queryRunner.query(`DROP TABLE "retro_cards"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_scope_sprint"`);
        await queryRunner.query(`DROP TABLE "sprint_scope_changes"`);
        await queryRunner.query(`DROP TABLE "sprint_daily_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac_work_item"`);
        await queryRunner.query(`DROP TABLE "work_item_acceptance_criteria"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_checklist_work_item"`);
        await queryRunner.query(`DROP TABLE "checklist_items"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_release_note_work_item"`);
        await queryRunner.query(`DROP TABLE "story_release_notes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assoc_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assoc_linked"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assoc_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_assoc_created_by"`);
        await queryRunner.query(`DROP TABLE "work_item_associations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_work_item_watchers_user"`);
        await queryRunner.query(`DROP TABLE "work_item_watchers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wi_project"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wi_parent"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wi_sprint"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wi_item_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wi_assignee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wi_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wi_project_number"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_wi_project_type"`);
        await queryRunner.query(`DROP TABLE "work_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_attachment_work_item"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_comment_work_item"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sprint_project"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_sprint_status"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_sprint_one_active_per_project"`);
        await queryRunner.query(`DROP TABLE "sprints"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_label_project"`);
        await queryRunner.query(`DROP TABLE "labels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ps_project"`);
        await queryRunner.query(`DROP TABLE "project_statuses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_project_status"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_pm_user"`);
        await queryRunner.query(`DROP TABLE "project_members"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_email"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE IF EXISTS "typeorm_metadata"`);
    }

}
