import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Restore the Phase-0 audit hardening that the pre-1.0 migration squash
 * dropped.
 *
 * The squashed Baseline was regenerated by TypeORM from the entity
 * metadata. The audit hardening (migrations 022/025/026/027/028) was
 * raw-SQL-only — it never lived on the entities — so the regeneration
 * silently lost it: the named association FK, the three CHECK
 * constraints, the eight cascade-policy FKs, and the FK-column indexes.
 * This migration re-applies all of it idempotently so a freshly-built
 * schema matches the audited production schema.
 *
 * Idempotency: every object is guarded (pg_constraint name lookup for
 * constraints, IF NOT EXISTS for indexes). Safe on fresh DBs and on
 * production DBs that already carry the hardening from the pre-squash
 * migrations.
 *
 * Indexes use plain CREATE INDEX (not CONCURRENTLY) so the whole
 * migration runs inside a single transaction — the original 028 ran
 * CONCURRENTLY to avoid write locks on a live table, but here the
 * objects already exist on every deployed DB (IF NOT EXISTS → no-op)
 * and fresh installs build against empty tables.
 */
export class RestoreAuditHardening1781600000000 implements MigrationInterface {
  name = 'RestoreAuditHardening1781600000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    // --- Association created_by FK: rename to the audited name --------
    // Baseline carries this FK under a TypeORM-generated name
    // (FK_<hash>) with the correct ON DELETE SET NULL policy. Drop any
    // FK currently on work_item_associations.created_by and re-add it
    // under the stable audited name FK_assoc_created_by.
    await queryRunner.query(`
      DO $$
      DECLARE conname_var text;
      BEGIN
        SELECT c.conname INTO conname_var
          FROM pg_constraint c
          JOIN pg_attribute a
            ON a.attrelid = c.conrelid AND a.attnum = ANY (c.conkey)
         WHERE c.conrelid = 'work_item_associations'::regclass
           AND c.contype = 'f'
           AND a.attname = 'created_by'
         LIMIT 1;
        IF conname_var IS NOT NULL AND conname_var <> 'FK_assoc_created_by' THEN
          EXECUTE format('ALTER TABLE "work_item_associations" DROP CONSTRAINT %I', conname_var);
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      ALTER TABLE "work_item_associations"
        ALTER COLUMN "created_by" DROP NOT NULL
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_assoc_created_by') THEN
          ALTER TABLE "work_item_associations"
            ADD CONSTRAINT "FK_assoc_created_by"
            FOREIGN KEY ("created_by") REFERENCES "users" ("id")
            ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$;
    `);

    // --- CHECK constraints (migration 025) ---------------------------
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_link_type') THEN
          ALTER TABLE work_item_associations
            ADD CONSTRAINT chk_link_type
            CHECK (link_type IN ('belongs_to','relates_to','blocks','caused_by'));
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_no_self_link') THEN
          ALTER TABLE work_item_associations
            ADD CONSTRAINT chk_no_self_link
            CHECK (item_id <> linked_item_id);
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_item_type') THEN
          ALTER TABLE work_items
            ADD CONSTRAINT chk_item_type
            CHECK (item_type IN ('epic','story','task','bug','subtask'));
        END IF;
      END $$;
    `);

    // --- Missing foreign keys (migration 027) ------------------------
    // retrospectives.created_by and sprints.created_by are already
    // nullable in the squashed Baseline; the SET NULL FKs below have a
    // valid target column without further ALTERs.
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_activity_work_item') THEN
          ALTER TABLE "activity_logs"
            ADD CONSTRAINT "FK_activity_work_item"
            FOREIGN KEY ("work_item_id") REFERENCES "work_items" ("id")
            ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_notif_project') THEN
          ALTER TABLE "notifications"
            ADD CONSTRAINT "FK_notif_project"
            FOREIGN KEY ("project_id") REFERENCES "projects" ("id")
            ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_invitation_project') THEN
          ALTER TABLE "invitations"
            ADD CONSTRAINT "FK_invitation_project"
            FOREIGN KEY ("project_id") REFERENCES "projects" ("id")
            ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_project_default_assignee') THEN
          ALTER TABLE "projects"
            ADD CONSTRAINT "FK_project_default_assignee"
            FOREIGN KEY ("default_assignee_id") REFERENCES "users" ("id")
            ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_retro_created_by') THEN
          ALTER TABLE "retrospectives"
            ADD CONSTRAINT "FK_retro_created_by"
            FOREIGN KEY ("created_by") REFERENCES "users" ("id")
            ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_sprint_created_by') THEN
          ALTER TABLE "sprints"
            ADD CONSTRAINT "FK_sprint_created_by"
            FOREIGN KEY ("created_by") REFERENCES "users" ("id")
            ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_project_member_added_by') THEN
          ALTER TABLE "project_members"
            ADD CONSTRAINT "FK_project_member_added_by"
            FOREIGN KEY ("added_by") REFERENCES "users" ("id")
            ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_scope_work_item') THEN
          ALTER TABLE "sprint_scope_changes"
            ADD CONSTRAINT "FK_scope_work_item"
            FOREIGN KEY ("work_item_id") REFERENCES "work_items" ("id")
            ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$;
    `);

    // --- FK-column indexes (migration 028) ---------------------------
    const indexStmts: ReadonlyArray<string> = [
      `CREATE INDEX IF NOT EXISTS "IDX_activity_logs_work_item_id" ON "activity_logs" ("work_item_id")`,
      `CREATE INDEX IF NOT EXISTS "IDX_activity_logs_user_id" ON "activity_logs" ("user_id")`,
      `CREATE INDEX IF NOT EXISTS "IDX_activity_logs_project_created" ON "activity_logs" ("project_id", "created_at" DESC)`,
      `CREATE INDEX IF NOT EXISTS "IDX_notifications_project_id" ON "notifications" ("project_id")`,
      `CREATE INDEX IF NOT EXISTS "IDX_notifications_user_unread" ON "notifications" ("user_id", "read_at") WHERE "read_at" IS NULL`,
      `CREATE INDEX IF NOT EXISTS "IDX_invitations_project_id" ON "invitations" ("project_id")`,
      `CREATE INDEX IF NOT EXISTS "IDX_invitations_invited_by" ON "invitations" ("invited_by")`,
      `CREATE INDEX IF NOT EXISTS "IDX_projects_default_assignee" ON "projects" ("default_assignee_id")`,
      `CREATE INDEX IF NOT EXISTS "IDX_retro_created_by" ON "retrospectives" ("created_by")`,
      `CREATE INDEX IF NOT EXISTS "IDX_sprints_created_by" ON "sprints" ("created_by")`,
      `CREATE INDEX IF NOT EXISTS "IDX_project_members_added_by" ON "project_members" ("added_by")`,
      `CREATE INDEX IF NOT EXISTS "IDX_sprint_scope_changes_work_item" ON "sprint_scope_changes" ("work_item_id")`,
      `CREATE INDEX IF NOT EXISTS "IDX_comments_work_item_created" ON "comments" ("work_item_id", "created_at" DESC)`,
      `CREATE INDEX IF NOT EXISTS "IDX_comments_author" ON "comments" ("author_id")`,
      `CREATE INDEX IF NOT EXISTS "IDX_attachments_uploaded_by" ON "attachments" ("uploaded_by")`,
    ];
    for (const sql of indexStmts) {
      await queryRunner.query(sql);
    }

    // Drop the duplicate retro_sprint index (overlaps the FK-implied
    // unique index on retrospectives.sprint_id).
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_retro_sprint"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Restore the duplicate index.
    await queryRunner.query(
      `CREATE UNIQUE INDEX IF NOT EXISTS "IDX_retro_sprint" ON "retrospectives" ("sprint_id")`,
    );

    const dropIndexes: ReadonlyArray<string> = [
      'IDX_attachments_uploaded_by',
      'IDX_comments_author',
      'IDX_comments_work_item_created',
      'IDX_sprint_scope_changes_work_item',
      'IDX_project_members_added_by',
      'IDX_sprints_created_by',
      'IDX_retro_created_by',
      'IDX_projects_default_assignee',
      'IDX_invitations_invited_by',
      'IDX_invitations_project_id',
      'IDX_notifications_user_unread',
      'IDX_notifications_project_id',
      'IDX_activity_logs_project_created',
      'IDX_activity_logs_user_id',
      'IDX_activity_logs_work_item_id',
    ];
    for (const name of dropIndexes) {
      await queryRunner.query(`DROP INDEX IF EXISTS "${name}"`);
    }

    const dropFks: ReadonlyArray<[string, string]> = [
      ['sprint_scope_changes', 'FK_scope_work_item'],
      ['project_members', 'FK_project_member_added_by'],
      ['sprints', 'FK_sprint_created_by'],
      ['retrospectives', 'FK_retro_created_by'],
      ['projects', 'FK_project_default_assignee'],
      ['invitations', 'FK_invitation_project'],
      ['notifications', 'FK_notif_project'],
      ['activity_logs', 'FK_activity_work_item'],
    ];
    for (const [table, name] of dropFks) {
      await queryRunner.query(
        `ALTER TABLE "${table}" DROP CONSTRAINT IF EXISTS "${name}"`,
      );
    }

    await queryRunner.query(
      `ALTER TABLE work_items DROP CONSTRAINT IF EXISTS chk_item_type`,
    );
    await queryRunner.query(
      `ALTER TABLE work_item_associations DROP CONSTRAINT IF EXISTS chk_no_self_link`,
    );
    await queryRunner.query(
      `ALTER TABLE work_item_associations DROP CONSTRAINT IF EXISTS chk_link_type`,
    );

    // Leave FK_assoc_created_by in place — renaming it back to the
    // generated Baseline name on rollback would require reproducing the
    // hash, and the SET NULL policy is identical either way.
  }
}
